// This file is automatically generated. Do not edit it directly.
import {createClient} from '@supabase/supabase-js';
import type {Database} from './types';

const SUPABASE_URL = "https://luvyhcckgznwfxccaqzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1dnloY2NrZ3pud2Z4Y2NhcXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NDMwODQsImV4cCI6MjA1NzQxOTA4NH0.oJxIzXAakxPFibxJgs8bC05wlzj6XanhIYOCVicvzYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);